apiVersion: v1
kind: Service
metadata:
  name: {{ include "workshop-exercise.fullname" . }}
  annotations:
    {{ include "helm3.annotations" . | nindent 4 }}
  labels:
    {{- include "workshop-exercise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workshop-exercise.selectorLabels" . | nindent 4 }}
